name = "Origins"
author = "Alina Shumann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfea7611457d83d995e3055c5b51c3c9abc90e46288c40c94ad89191f8198b5b"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
